### ISSUE TITLE
[Mod Support Request] Mekanism

### ISSUE THREAD

**Issue by SillySoon** [nebuIr/Default-Dark-Mode#58] opened 2022-11-11 01:04 UTC
### Description

Basically All mekanism GUI's, especially for the 1.18.2

Fox example:
![grafik](https://user-images.githubusercontent.com/57587656/201238192-35915a3a-8e7a-401f-a05b-35566dadacfb.png)

### Link to the mod page

https://www.curseforge.com/minecraft/mc-mods/mekanism

### Game versions

1.18

### Modloaders

Forge

**Comment by nebuIr** [comment] 2023-05-15 17:34
Duplicate of [#46](https://github.com/nebuIr/Default-Dark-Mode/issues/46)

**Closed by nebuIr** 2023-05-15 17:34 UTC
Labels: 🧩 mod-support
