### ISSUE TITLE
[Mod Support Request] PlayerEx

### ISSUE THREAD

**Issue by yonatandeneke** [nebuIr/Default-Dark-Mode#113] opened 2023-04-21 04:49 UTC
### Description

Inventory tabs is white

### Link to the mod page

https://www.curseforge.com/minecraft/mc-mods/playerex

### Game versions

1.19

### Modloaders

Fabric

**Comment by nebuIr** [comment] 2023-05-15 17:33
Duplicate of [#61](https://github.com/nebuIr/Default-Dark-Mode/issues/61)

**Closed by nebuIr** 2023-05-15 17:33 UTC
Labels: 🧩 mod-support
